In [1]:
# Import the Libraries
import numpy as np
import pandas as pd
from sklearn import linear_model, metrics
from sklearn.linear_model import LogisticRegression

In [2]:
# Import the Data
train_data = pd.read_csv('./TrainingSet.csv', index_col=0)
train_data.head()

             Open Price  Close Price  High Price  Low Price      Volume
Date
02-Jan-2009      902.99       931.80      934.73     899.35  4048270080
05-Jan-2009      929.17       927.45      936.63     919.53  5413910016
06-Jan-2009      931.17       934.70      943.85     927.28  5392620032
07-Jan-2009      927.45       906.65      927.45     902.37  4704940032
08-Jan-2009      905.73       909.73      910.00     896.81  4991549952

In [3]:
# Import the Data
test_data = pd.read_csv('./TestSet.csv', index_col=0)
test_data.head()

             Open Price  Close Price  High Price  Low Price      Volume
Date
02-Jan-2018     2683.73      2695.81     2695.89    2682.36  1846463232
03-Jan-2018     2697.85      2713.06     2714.37    2697.77  2090595328
04-Jan-2018     2719.31      2723.99     2729.29    2719.07  2100767744
05-Jan-2018     2731.33      2743.15     2743.45    2727.92  1918869120
08-Jan-2018     2742.67      2747.71     2748.51    2737.60  1894823936

In [4]:
# Define Predictor/Independent Variables
train_data['Open - Open'] = train_data['Open Price'] - train_data['Open Price'].shift(1)
train_data['Close - Close'] = train_data['Close Price'] - train_data['Close Price'].shift(1)
train_data = train_data.dropna()
x_train = train_data
x_train.head()

,Open Price,Close Price,High Price,Low Price,Volume,Open - Open,Close - Close
Date,,,,,,,
05-Jan-2009,929.17,927.45,936.63,919.53,5413910016,26.18,-4.35
06-Jan-2009,931.17,934.70,943.85,927.28,5392620032,2.00,7.25
07-Jan-2009,927.45,906.65,927.45,902.37,4704940032,-3.72,-28.05
08-Jan-2009,905.73,909.73,910.00,896.81,4991549952,-21.72,3.08
09-Jan-2009,909.91,890.35,911.93,888.31,4716499968,4.18,-19.38

In [5]:
# Define Predictor/Independent Variables
test_data['Open - Open'] = test_data['Open Price'] - test_data['Open Price'].shift(1)
test_data['Close - Close'] = test_data['Close Price'] - test_data['Close Price'].shift(1)
test_data = test_data.dropna()
x_test = test_data
x_test.head()

,Open Price,Close Price,High Price,Low Price,Volume,Open - Open,Close - Close
Date,,,,,,,
03-Jan-2018,2697.85,2713.06,2714.37,2697.77,2090595328,14.12,17.25
04-Jan-2018,2719.31,2723.99,2729.29,2719.07,2100767744,21.46,10.93
05-Jan-2018,2731.33,2743.15,2743.45,2727.92,1918869120,12.02,19.16
08-Jan-2018,2742.67,2747.71,2748.51,2737.60,1894823936,11.34,4.56
09-Jan-2018,2751.15,2751.29,2759.14,2747.86,1957263872,8.48,3.58

In [6]:
# Define Target/Dependent Variable
y_train = np.where(train_data['Close Price'].shift(-1) > train_data['Close Price'], 1, -1)
print(y_train)

[ 1 -1  1 ...  1 -1 -1]

In [7]:
# Define Target/Dependent Variable
y_test = np.where(test_data['Close Price'].shift(-1) > test_data['Close Price'], 1, -1)
print(y_test)

[ 1  1  1  1 -1  1  1 -1  1 -1  1  1  1 -1  1  1 -1 -1  1 -1 -1 -1  1 -1
 -1  1  1  1  1  1  1 -1 -1  1  1  1 -1 -1 -1  1  1  1 -1  1  1 -1 -1 -1
 -1  1 -1  1 -1 -1 -1  1 -1 -1  1 -1  1  1  1 -1  1  1 -1  1 -1  1  1  1
 -1 -1  1 -1  1  1  1 -1  1 -1 -1  1  1 -1  1  1  1  1 -1  1 -1 -1  1 -1
  1 -1 -1 -1  1 -1  1  1  1  1 -1  1  1  1 -1  1 -1 -1 -1  1 -1  1 -1  1
 -1  1  1  1 -1  1  1  1  1 -1  1  1 -1  1  1 -1 -1  1  1  1 -1 -1 -1  1
 -1  1  1  1  1 -1 -1 -1 -1  1 -1  1  1  1  1 -1 -1  1  1  1  1 -1  1 -1
 -1 -1 -1  1  1  1  1  1 -1  1  1  1 -1 -1 -1 -1  1 -1  1 -1  1 -1 -1 -1
 -1 -1 -1  1 -1  1 -1 -1 -1 -1 -1 -1  1 -1 -1  1  1  1 -1  1  1  1 -1 -1
 -1 -1 -1  1  1 -1 -1  1 -1  1  1  1 -1  1  1 -1 -1 -1 -1  1 -1  1 -1 -1
 -1  1 -1 -1 -1 -1  1  1 -1  1 -1]

In [8]:
# Fit the Model
model = LogisticRegression(random_state=0, solver='lbfgs', multi_class='multinomial').fit(x_train, y_train)

In [9]:
# Predict Class
predict_class = model.predict(x_test)
print(predict_class)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]

In [10]:
# Predict Probability
predict_prob = model.predict_proba(x_test)
print(predict_prob)

[[0.47078045 0.52921955]
 [0.4706386  0.5293614 ]
 [0.47317579 0.52682421]
 [0.47351129 0.52648871]
 [0.47264013 0.52735987]
 [0.47136238 0.52863762]
 [0.47234259 0.52765741]
 [0.47053185 0.52946815]
 [0.464628   0.535372  ]
 [0.4670399  0.5329601 ]
 [0.46913823 0.53086177]
 [0.46681968 0.53318032]
 [0.47081412 0.52918588]
 [0.46995238 0.53004762]
 [0.46659103 0.53340897]
 [0.46799678 0.53200322]
 [0.46982476 0.53017524]
 [0.47083886 0.52916114]
 [0.4673062  0.5326938 ]
 [0.46299599 0.53700401]
 [0.46638364 0.53361636]
 [0.46326995 0.53673005]
 [0.45273163 0.54726837]
 [0.44630878 0.55369122]
 [0.4615499  0.5384501 ]
 [0.45574352 0.54425648]
 [0.44959941 0.55040059]
 [0.46405919 0.53594081]
 [0.47194692 0.52805308]
 [0.4672918  0.5327082 ]
 [0.46900603 0.53099397]
 [0.46985811 0.53014189]
 [0.47113538 0.52886462]
 [0.46990085 0.53009915]
 [0.471258   0.528742  ]
 [0.47417684 0.52582316]
 [0.47108043 0.52891957]
 [0.46755142 0.53244858]
 [0.46478497 0.53521503]
 [0.46191585 0.53808415]
 [0.46688271 0.53311729]
 [0.46783318 0.53216682]
 [0.47169794 0.52830206]
 [0.47137431 0.52862569]
 [0.47307816 0.52692184]
 [0.47110155 0.52889845]
 [0.47111846 0.52888154]
 [0.46951212 0.53048788]
 [0.47092843 0.52907157]
 [0.47294335 0.52705665]
 [0.45370243 0.54629757]
 [0.47028082 0.52971918]
 [0.47149777 0.52850223]
 [0.47141542 0.52858458]
 [0.46607444 0.53392556]
 [0.46535961 0.53464039]
 [0.46711212 0.53288788]
 [0.46581814 0.53418186]
 [0.46534963 0.53465037]
 [0.46786938 0.53213062]
 [0.46635707 0.53364293]
 [0.47063783 0.52936217]
 [0.46991709 0.53008291]
 [0.47283262 0.52716738]
 [0.4708463  0.5291537 ]
 [0.47415369 0.52584631]
 [0.47076758 0.52923242]
 [0.47566128 0.52433872]
 [0.47333759 0.52666241]
 [0.47487239 0.52512761]
 [0.47424415 0.52575585]
 [0.47316466 0.52683534]
 [0.47223503 0.52776497]
 [0.47006099 0.52993901]
 [0.46815167 0.53184833]
 [0.47440284 0.52559716]
 [0.46704751 0.53295249]
 [0.47020382 0.52979618]
 [0.46729645 0.53270355]
 [0.47158392 0.52841608]
 [0.46875378 0.53124622]
 [0.47062537 0.52937463]
 [0.46804794 0.53195206]
 [0.46728061 0.53271939]
 [0.47354864 0.52645136]
 [0.47390753 0.52609247]
 [0.47121884 0.52878116]
 [0.47154098 0.52845902]
 [0.47528743 0.52471257]
 [0.47585588 0.52414412]
 [0.47515711 0.52484289]
 [0.47333697 0.52666303]
 [0.47515201 0.52484799]
 [0.47347355 0.52652645]
 [0.47255768 0.52744232]
 [0.47459034 0.52540966]
 [0.47217782 0.52782218]
 [0.47143825 0.52856175]
 [0.47307807 0.52692193]
 [0.47674303 0.52325697]
 [0.46952201 0.53047799]
 [0.47244702 0.52755298]
 [0.46330884 0.53669116]
 [0.47336976 0.52663024]
 [0.47373687 0.52626313]
 [0.47324834 0.52675166]
 [0.47160294 0.52839706]
 [0.47188569 0.52811431]
 [0.47591436 0.52408564]
 [0.47504816 0.52495184]
 [0.47371485 0.52628515]
 [0.46782151 0.53217849]
 [0.47065574 0.52934426]
 [0.45360525 0.54639475]
 [0.4731945  0.5268055 ]
 [0.47120365 0.52879635]
 [0.47089936 0.52910064]
 [0.47117229 0.52882771]
 [0.46117567 0.53882433]
 [0.46817614 0.53182386]
 [0.46996813 0.53003187]
 [0.46890934 0.53109066]
 [0.47144329 0.52855671]
 [0.46961388 0.53038612]
 [0.47589294 0.52410706]
 [0.48433573 0.51566427]
 [0.47655629 0.52344371]
 [0.47887662 0.52112338]
 [0.47621484 0.52378516]
 [0.47670593 0.52329407]
 [0.4751048  0.5248952 ]
 [0.4746553  0.5253447 ]
 [0.47605783 0.52394217]
 [0.47563066 0.52436934]
 [0.47473468 0.52526532]
 [0.4735763  0.5264237 ]
 [0.47108536 0.52891464]
 [0.47188036 0.52811964]
 [0.47497406 0.52502594]
 [0.47065986 0.52934014]
 [0.46915574 0.53084426]
 [0.46721826 0.53278174]
 [0.46985295 0.53014705]
 [0.47169814 0.52830186]
 [0.46799182 0.53200818]
 [0.4704824  0.5295176 ]
 [0.47278645 0.52721355]
 [0.47523033 0.52476967]
 [0.4765814  0.5234186 ]
 [0.47616894 0.52383106]
 [0.47796481 0.52203519]
 [0.47697751 0.52302249]
 [0.47539779 0.52460221]
 [0.47561632 0.52438368]
 [0.47699257 0.52300743]
 [0.47060112 0.52939888]
 [0.47360779 0.52639221]
 [0.47468511 0.52531489]
 [0.47749545 0.52250455]
 [0.47501023 0.52498977]
 [0.47838564 0.52161436]
 [0.47882888 0.52117112]
 [0.47935629 0.52064371]
 [0.47626538 0.52373462]
 [0.47848097 0.52151903]
 [0.47805433 0.52194567]
 [0.47716781 0.52283219]
 [0.47613629 0.52386371]
 [0.47466459 0.52533541]
 [0.47201836 0.52798164]
 [0.4736308  0.5263692 ]
 [0.47490593 0.52509407]
 [0.47779762 0.52220238]
 [0.47646525 0.52353475]
 [0.47394134 0.52605866]
 [0.47413188 0.52586812]
 [0.4766752  0.5233248 ]
 [0.47723318 0.52276682]
 [0.4754925  0.5245075 ]
 [0.47512515 0.52487485]
 [0.47251016 0.52748984]
 [0.44905049 0.55094951]
 [0.47263268 0.52736732]
 [0.47379241 0.52620759]
 [0.47271244 0.52728756]
 [0.47592529 0.52407471]
 [0.47220122 0.52779878]
 [0.47224771 0.52775229]
 [0.47378647 0.52621353]
 [0.47353329 0.52646671]
 [0.47217441 0.52782559]
 [0.47271931 0.52728069]
 [0.47368171 0.52631829]
 [0.47182595 0.52817405]
 [0.462379   0.537621  ]
 [0.45675501 0.54324499]
 [0.46495072 0.53504928]
 [0.47306207 0.52693793]
 [0.47167318 0.52832682]
 [0.47216012 0.52783988]
 [0.46896411 0.53103589]
 [0.46811349 0.53188651]
 [0.47130148 0.52869852]
 [0.46321338 0.53678662]
 [0.45894612 0.54105388]
 [0.46191203 0.53808797]
 [0.45725717 0.54274283]
 [0.46139114 0.53860886]
 [0.45523555 0.54476445]
 [0.45750186 0.54249814]
 [0.46360852 0.53639148]
 [0.46257781 0.53742219]
 [0.47108553 0.52891447]
 [0.47305708 0.52694292]
 [0.46873796 0.53126204]
 [0.47093782 0.52906218]
 [0.46668662 0.53331338]
 [0.46811303 0.53188697]
 [0.46753818 0.53246182]
 [0.46501121 0.53498879]
 [0.4641849  0.5358151 ]
 [0.46483584 0.53516416]
 [0.4668378  0.5331622 ]
 [0.46154302 0.53845698]
 [0.47283359 0.52716641]
 [0.48668705 0.51331295]
 [0.47046259 0.52953741]
 [0.47135124 0.52864876]
 [0.46774529 0.53225471]
 [0.47236753 0.52763247]
 [0.46045763 0.53954237]
 [0.46439182 0.53560818]
 [0.46070724 0.53929276]
 [0.46008086 0.53991914]
 [0.45651805 0.54348195]
 [0.465671   0.534329  ]
 [0.46598578 0.53401422]
 [0.46865778 0.53134222]
 [0.46779799 0.53220201]
 [0.46867581 0.53132419]
 [0.46605372 0.53394628]
 [0.46207569 0.53792431]
 [0.46333624 0.53666376]
 [0.45501359 0.54498641]
 [0.452158   0.547842  ]
 [0.43653556 0.56346444]
 [0.47675044 0.52324956]
 [0.463518   0.536482  ]
 [0.46665667 0.53334333]
 [0.47091807 0.52908193]
 [0.47326214 0.52673786]]

In [11]:
# Evaluate
predict_acc = model.score(x_test, y_test)
print(predict_acc)

0.5179282868525896